export const userListData = {
  pageMeta: {
    totalItems: 50,
    totalPages: 5,
    currentPage: 1,
    limit: 10,
  },

  data: [
    {
      id: 1,
      user: "Dr. James Smith",
      email: "j.smith@medicare.com",
      initials: "JS",
      role: "Surgeon",
      status: "Active",
      lastLogin: "2025-01-12 09:15 AM",
      twoFA: "Enabled",
    },
    {
      id: 2,
      user: "Sarah Johnson",
      email: "s.johnson@medicare.com",
      initials: "SJ",
      role: "Coordinator",
      status: "Active",
      lastLogin: "2025-01-11 04:30 PM",
      twoFA: "Disabled",
    },
    {
      id: 3,
      user: "Michael Chen",
      email: "m.chen@medicare.com",
      initials: "MC",
      role: "Nurse",
      status: "Suspended",
      lastLogin: "2025-01-05 11:20 AM",
      twoFA: "Enabled",
    },
    {
      id: 4,
      user: "Emma Davis",
      email: "e.davis@medicare.com",
      initials: "ED",
      role: "Admin",
      status: "Active",
      lastLogin: "2025-01-10 02:45 PM",
      twoFA: "Enabled",
    },
    {
      id: 5,
      user: "Olivia Brown",
      email: "o.brown@medicare.com",
      initials: "OB",
      role: "Receptionist",
      status: "Disabled",
      lastLogin: "2024-12-25 08:10 AM",
      twoFA: "Disabled",
    },
    {
      id: 6,
      user: "Daniel Foster",
      email: "d.foster@medicare.com",
      initials: "DF",
      role: "Coordinator",
      status: "Active",
      lastLogin: "2025-01-09 10:40 AM",
      twoFA: "Enabled",
    },
    {
      id: 7,
      user: "Ava Thompson",
      email: "a.thompson@medicare.com",
      initials: "AT",
      role: "Nurse",
      status: "Active",
      lastLogin: "2025-01-11 01:22 PM",
      twoFA: "Disabled",
    },
    {
      id: 8,
      user: "James Carter",
      email: "j.carter@medicare.com",
      initials: "JC",
      role: "Admin",
      status: "Suspended",
      lastLogin: "2025-01-03 05:15 PM",
      twoFA: "Enabled",
    },
    {
      id: 9,
      user: "Sophia Martinez",
      email: "s.martinez@medicare.com",
      initials: "SM",
      role: "Receptionist",
      status: "Active",
      lastLogin: "2025-01-12 07:50 AM",
      twoFA: "Enabled",
    },
  ],
};
