
export const patientTasks = {
  pageMeta: {
    totalItems: 40,
    totalPages: 4,
    currentPage: 1,
    limit: 10,
  },
  data: [
    {
      id: 1,
      patientName: "Sarah Johnson",
      procedureType: "Rhinoplasty",
      phase: "Pre-Op",
      taskName: "Complete consent forms",
      status: "In Progress",
      dueDate: "2025-11-02",
      assignee: "Jane Williams",
    },
    {
      id: 2,
      patientName: "Michael Chen",
      procedureType: "Breast Augmentation",
      phase: "Post-Op",
      taskName: "Schedule follow-up appointment",
      status: "In Progress",
      dueDate: "2025-11-01",
      assignee: "Dr. Smith",
    },
    {
      id: 3,
      patientName: "Emma Davis",
      procedureType: "Liposuction",
      phase: "Consultation",
      taskName: "Send procedure information pack",
      status: "Overdue",
      dueDate: "2025-10-28",
      assignee: "Admin Team",
    },
    {
      id: 4,
      patientName: "Oliver Brown",
      procedureType: "Facelift",
      phase: "Pre-Op",
      taskName: "Medical clearance review",
      status: "Completed",
      dueDate: "2025-10-29",
      assignee: "Nurse Kelly",
    },
    {
      id: 5,
      patientName: "Laura Mitchell",
      procedureType: "Tummy Tuck",
      phase: "Pre-Op",
      taskName: "Upload lab reports",
      status: "Pending",
      dueDate: "2025-11-05",
      assignee: "Admin Team",
    },
    {
      id: 6,
      patientName: "Daniel Foster",
      procedureType: "Gynecomastia",
      phase: "Consultation",
      taskName: "Confirm consultation time",
      status: "In Progress",
      dueDate: "2025-11-03",
      assignee: "Reception Desk",
    },
    {
      id: 7,
      patientName: "Ava Thompson",
      procedureType: "Breast Lift",
      phase: "Post-Op",
      taskName: "Wound check follow-up",
      status: "Pending",
      dueDate: "2025-11-06",
      assignee: "Nurse Kelly",
    },
    {
      id: 8,
      patientName: "James Carter",
      procedureType: "Chin Augmentation",
      phase: "Pre-Op",
      taskName: "Upload medical history",
      status: "Completed",
      dueDate: "2025-10-26",
      assignee: "Admin Team",
    },
    {
      id: 9,
      patientName: "Sophia Martinez",
      procedureType: "Rhinoplasty",
      phase: "Post-Op",
      taskName: "Pain management follow-up",
      status: "In Progress",
      dueDate: "2025-11-04",
      assignee: "Dr. Patel",
    },
    {
      id: 10,
      patientName: "Liam Anderson",
      procedureType: "Neck Lift",
      phase: "Consultation",
      taskName: "Share pre-surgery instructions",
      status: "Pending",
      dueDate: "2025-11-07",
      assignee: "Admin Team",
    },
    {
      id: 11,
      patientName: "Chloe Rivera",
      procedureType: "Blepharoplasty",
      phase: "Pre-Op",
      taskName: "Review anesthesia notes",
      status: "In Progress",
      dueDate: "2025-11-02",
      assignee: "Dr. Williams",
    },
    {
      id: 12,
      patientName: "Henry Walker",
      procedureType: "Hair Transplant",
      phase: "Post-Op",
      taskName: "Update graft count report",
      status: "Completed",
      dueDate: "2025-10-22",
      assignee: "Nurse Team",
    },
    {
      id: 13,
      patientName: "Isabella Clark",
      procedureType: "Breast Augmentation",
      phase: "Consultation",
      taskName: "Send cost estimate",
      status: "Pending",
      dueDate: "2025-11-08",
      assignee: "Admin Team",
    },
    {
      id: 14,
      patientName: "Noah Hall",
      procedureType: "Liposuction",
      phase: "Pre-Op",
      taskName: "Check blood pressure report",
      status: "Overdue",
      dueDate: "2025-10-27",
      assignee: "Nurse David",
    },
    {
      id: 15,
      patientName: "Grace Lewis",
      procedureType: "Tummy Tuck",
      phase: "Post-Op",
      taskName: "Schedule suture removal",
      status: "Pending",
      dueDate: "2025-11-09",
      assignee: "Dr. Smith",
    },
    {
      id: 16,
      patientName: "Ethan White",
      procedureType: "Facelift",
      phase: "Consultation",
      taskName: "Confirm medical questionnaire",
      status: "In Progress",
      dueDate: "2025-11-03",
      assignee: "Admin Team",
    },
    {
      id: 17,
      patientName: "Mia Young",
      procedureType: "Breast Reduction",
      phase: "Pre-Op",
      taskName: "Sign consent documents",
      status: "Pending",
      dueDate: "2025-11-05",
      assignee: "Admin Team",
    },
    {
      id: 18,
      patientName: "Logan King",
      procedureType: "Chin Augmentation",
      phase: "Post-Op",
      taskName: "Follow-up wound check",
      status: "In Progress",
      dueDate: "2025-11-06",
      assignee: "Nurse Kelly",
    },
    {
      id: 19,
      patientName: "Harper Scott",
      procedureType: "Rhinoplasty",
      phase: "Consultation",
      taskName: "Send before/after samples",
      status: "Pending",
      dueDate: "2025-11-10",
      assignee: "Admin Team",
    },
    {
      id: 20,
      patientName: "Lucas Green",
      procedureType: "Blepharoplasty",
      phase: "Post-Op",
      taskName: "Check eye swelling",
      status: "Overdue",
      dueDate: "2025-10-30",
      assignee: "Nurse David",
    },
    {
      id: 21,
      patientName: "Ella Perez",
      procedureType: "Liposuction",
      phase: "Pre-Op",
      taskName: "Update BMI details",
      status: "Pending",
      dueDate: "2025-11-12",
      assignee: "Admin Team",
    },
    {
      id: 22,
      patientName: "Nathan Campbell",
      procedureType: "Hair Transplant",
      phase: "Consultation",
      taskName: "Share graft plan",
      status: "In Progress",
      dueDate: "2025-11-06",
      assignee: "Dr. Patel",
    },
    {
      id: 23,
      patientName: "Aria Edwards",
      procedureType: "Breast Lift",
      phase: "Pre-Op",
      taskName: "Review medication list",
      status: "Completed",
      dueDate: "2025-10-24",
      assignee: "Nurse Kelly",
    },
    {
      id: 24,
      patientName: "Benjamin Turner",
      procedureType: "Rhinoplasty",
      phase: "Post-Op",
      taskName: "Update progress notes",
      status: "Pending",
      dueDate: "2025-11-11",
      assignee: "Nurse Team",
    },
    {
      id: 25,
      patientName: "Luna Morgan",
      procedureType: "Tummy Tuck",
      phase: "Consultation",
      taskName: "Send payment options",
      status: "Pending",
      dueDate: "2025-11-13",
      assignee: "Admin Team",
    },
    {
      id: 26,
      patientName: "Jacob Wood",
      procedureType: "Gynecomastia",
      phase: "Pre-Op",
      taskName: "Confirm lab sample receipt",
      status: "In Progress",
      dueDate: "2025-11-04",
      assignee: "Admin Team",
    },
    {
      id: 27,
      patientName: "Scarlett Hughes",
      procedureType: "Facelift",
      phase: "Post-Op",
      taskName: "Monitor bruising",
      status: "Pending",
      dueDate: "2025-11-12",
      assignee: "Nurse David",
    },
    {
      id: 28,
      patientName: "Owen Cox",
      procedureType: "Liposuction",
      phase: "Consultation",
      taskName: "Send surgeon availability",
      status: "Completed",
      dueDate: "2025-10-18",
      assignee: "Admin Team",
    },
    {
      id: 29,
      patientName: "Amelia Ward",
      procedureType: "Blepharoplasty",
      phase: "Pre-Op",
      taskName: "Check allergy history",
      status: "In Progress",
      dueDate: "2025-11-02",
      assignee: "Dr. Williams",
    },
    {
      id: 30,
      patientName: "Matthew Ross",
      procedureType: "Chin Augmentation",
      phase: "Post-Op",
      taskName: "Track swelling reduction",
      status: "Pending",
      dueDate: "2025-11-10",
      assignee: "Nurse Kelly",
    },
    {
      id: 31,
      patientName: "Avery Price",
      procedureType: "Tummy Tuck",
      phase: "Pre-Op",
      taskName: "Review ECG report",
      status: "Pending",
      dueDate: "2025-11-14",
      assignee: "clinic Admin",
    },
    {
      id: 32,
      patientName: "Wyatt Rivera",
      procedureType: "Hair Transplant",
      phase: "Post-Op",
      taskName: "Update donor site notes",
      status: "Completed",
      dueDate: "2025-10-20",
      assignee: "Nurse Team",
    },
    {
      id: 33,
      patientName: "Layla Simmons",
      procedureType: "Breast Reduction",
      phase: "Consultation",
      taskName: "Send surgery guide",
      status: "Pending",
      dueDate: "2025-11-16",
      assignee: "Admin Team",
    },
    {
      id: 34,
      patientName: "Jack Foster",
      procedureType: "Facelift",
      phase: "Pre-Op",
      taskName: "Review prior medical history",
      status: "In Progress",
      dueDate: "2025-11-03",
      assignee: "Dr. Smith",
    },
    {
      id: 35,
      patientName: "Victoria Hayes",
      procedureType: "Rhinoplasty",
      phase: "Post-Op",
      taskName: "Check nasal splint",
      status: "Pending",
      dueDate: "2025-11-11",
      assignee: "Nurse David",
    },
    {
      id: 36,
      patientName: "Carter Brooks",
      procedureType: "Gynecomastia",
      phase: "Post-Op",
      taskName: "Pain medication update",
      status: "Overdue",
      dueDate: "2025-10-31",
      assignee: "Dr. Patel",
    },
    {
      id: 37,
      patientName: "Hannah Reed",
      procedureType: "Liposuction",
      phase: "Pre-Op",
      taskName: "Confirm anesthesia type",
      status: "Pending",
      dueDate: "2025-11-15",
      assignee: "Dr. Williams",
    },
    {
      id: 38,
      patientName: "Elijah Baker",
      procedureType: "Tummy Tuck",
      phase: "Consultation",
      taskName: "Arrange virtual consultation",
      status: "Completed",
      dueDate: "2025-10-19",
      assignee: "Reception Desk",
    },
    {
      id: 39,
      patientName: "Natalie Griffin",
      procedureType: "Breast Lift",
      phase: "Post-Op",
      taskName: "Monitor healing progress",
      status: "On Track",
      dueDate: "2025-11-17",
      assignee: "clinic Admin",
    },
    {
      id: 40,
      patientName: "Adam Morgan",
      procedureType: "Chin Augmentation",
      phase: "Pre-Op",
      taskName: "Schedule pre-op call",
      status: "Needs Attention",
      dueDate: "2025-11-06",
      assignee: "Admin Team",
    },
  ],
};
