export const API_ENDPOINTS = {
  OPERATIONS_SERVICE: {
    USER_DATA_FETCH: `/api/v1/auth/user-data`,
    USER_LIST_FETCH: `/api/v1/auth/user-list`,
    SYNC_USER: `/api/v1/auth/sync-user`,
    UPDATE_PATIENT_PHASE: `/api/v1/auth/update-patient-phase`,
    FIND_USER_BY_NAME_OR_EMAIL: `/api/v1/auth/user-by-email-or-name`,
    UPDATE_PATIENT_PHASE_WEBHOOK: `/api/v1/auth/update-patient-phase-webhook`,
    FIND_USER_BY_EMAILS: `/api/v1/auth/user-by-emails`,
  },
  CONTENT_SERVICE: {
    TASK_AUTOMATION: `/api/v1/tasks/task-automation`,
    WEBHOOK_TASK_AUTOMATION: `/api/v1/tasks/webhook-task-automation`,
    DROPDOWN_FETCH: `/api/v1/dropdowns`,
    FORMS_FETCH: `/api/v1/forms`,
    ELEARNINGS_FETCH: `/api/v1/elearnings`,
    TASK_AUTO_CREATE: `/api/v1/tasks/auto-create`,
    WEBHOOK_SYNC: `/api/v1/form_response/webhook-sync`,
    WEBHOOK_SYNC_NEW: `/api/v1/form_response/webhook-sync-new`,
    REPORTS_STAFF: {
      DASHBOARD_CARDS_STAFFS: `/api/v1/Reports-staffs/dashboard-cards-staffs`,
      DASHBOARD_WEEKLY_FORM_APPROVALS: `/api/v1/Reports-staffs/dashboard-weekly-formApprovals`,
      RESPONSE_TIME_TREND: `/api/v1/Reports-staffs/response-time-trend`,
      FORM_TYPE_BREAKDOWN: `/api/v1/Reports-staffs/form-type-breakdown`,
      PERFORMANCE_SUMMARY: `/api/v1/Reports-staffs/performance-summary`,
      EXPORT_REPORTS_STAFF: `/api/v1/Reports-staffs/export-report-staff`,
    },
    REPORTS_ADMIN: {
      DASHBOARD_CARDS: `/api/v1/reports-admin/dashboard-cards`,
      HEADCOUNT: `/api/v1/reports-admin/headcount`,
      PERFORMANCE_BY_USER: `/api/v1/reports-admin/performance-by-user`,
      CONTENT_PERFORMANCE: `/api/v1/reports-admin/content-performance`,
      APP_ENGAGEMENT_TREND: `/api/v1/reports-admin/app-engagement-trends`,
      ALL_REPORTS_DATA: `/api/v1/reports-admin/export-report-data`,
    },
    SEARCH_THREADS_BULK: `/api/v1/Message/threads/search-bulk`,
    WEBHOOK_SYNC_MAPPED: `/api/v1/form_response/webhook-sync-mapped`,
  },
  ZOHO_SERVICE: {
    OAUTH_TOKEN_URL: 'https://accounts.zoho.com/oauth/v2/token',
    APPOINTMENTS: `/api/v1/zoho/appointments`,
    APPOINTMENTS_VIA_EMAIL: '/api/v1/zoho/appointments-via-email',
    CRM_APPOINTMENTS_SEARCH: '/crm/v8/Consultation_Appointments/search',
    CRM_CLINICIANS_SEARCH: '/crm/v8/Clinician_s/search',
    CRM_COSM_SURGERY_SEARCH: '/crm/v8/Cosm_Surgery/search',
    GENERATE_TOKEN: '/api/v1/zoho/generate-token',
    GENERATE_FORM_TOKEN: '/api/v1/zoho/generate-form-token',
    WEBHOOK_FORM: '/api/v1/zoho/webhook/form',
  },
  ZOHO_FORM_SERVICE: {
    ASK_THE_SURGEON: '/api/v1/zoho-forms/submit-zoho-askthesurgeon',
    ASK_THE_TEAM: '/api/v1/zoho-forms/submit-zoho-asktheteam',
    SSQ: '/api/v1/zoho-forms/submit-zoho-ssq',
    POST_OPS: '/api/v1/zoho-forms/submit-zoho-post-ops',
    GET_PATIENT_FORMS: '/api/v1/webhooks/patient-forms/helper',
  },
  NOTIFICATION_SEND_OTP_EMAIL: `/api/v1/notifications`,
};
