import { CommonButton, CommonIcon, Modal } from "@/components/common";
import { toast } from "@/utils/toast";
import { Box, Typography, useTheme } from "@mui/material";
import { useNotificationRule } from "../../hooks/editNotification";

interface NotificationRuleModalProps {
  open: boolean;
  onClose: () => void;
  ruleId: string | null;
  ruleName?: string;
  onDeleteSuccess: () => void;
}

export default function DeleteNotificationRuleModal({
  open,
  onClose,
  ruleId,
  ruleName,
  onDeleteSuccess,
}: NotificationRuleModalProps) {
  const theme = useTheme();

  // Use the hook with the ruleId
  const { deleteNotificationRule, deleting } = useNotificationRule(
    ruleId || undefined
  );

  const handleDelete = async () => {
    if (!ruleId) return;

    try {
      await deleteNotificationRule();
      toast.success("Notification rule deleted successfully");
      console.log(onDeleteSuccess, "delete id ");
      onDeleteSuccess();
      onClose();
    } catch (error) {
      toast.error("Failed to delete notification rule");
      console.error("Delete error:", error);
    }
  };

  return (
    <Modal open={open} onClose={onClose}>
      <Box
        sx={{
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          // textAlign: "center",
          gap: "24px",
          margin: "0 auto",
        }}
      >
        <Typography
          variant="h3"
          fontWeight={600}
          color={theme.palette.text.primary}
        >
          Delete Notification Rule?
        </Typography>
        <Box
          sx={{
            width: 80,
            height: 80,
            borderRadius: "50%",
            border: `2px solid ${theme.palette.primary.main}`,
            bgcolor: "#FEFBF1",
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
          }}
        >
          <CommonIcon
            name="Trash2"
            size={46}
            color={theme.palette.primary.main}
          />
        </Box>

        <Typography variant="body1" color={theme.palette.text.secondary}>
          You are about to delete "{ruleName || ruleName}"
        </Typography>

        <Box
          sx={{
            p: 2.5,
            borderRadius: "12px",
            bgcolor: "#FDECEA",
            border: "1px solid #F5C2C7",
          }}
        >
          {/* Header */}
          <Box sx={{ display: "flex", alignItems: "center", gap: 1, mb: 1.5 }}>
            <CommonIcon name="AlertTriangle" color="red" size={20} />
            <Typography sx={{ color: "error.main", fontWeight: 700 }}>
              Warning
            </Typography>
          </Box>
          <Typography
            sx={{
              display: "flex",
              flexDirection: "column",
              color: "error.dark",
              fontSize: 15,
              lineHeight: 1.4,
              px: 3
            }}
          >
            This will stop all alerts generated by this rule immediately. This action is permanent.
          </Typography>
        </Box>

        <Box sx={{ width: "100%", mt: 1 }}>
          <CommonButton
            fullWidth
            variant="contained"
            color="error"
            loading={deleting}
            onClick={handleDelete}
            disabled={deleting}
          >
            Delete Rule
          </CommonButton>

          {/* CANCEL BUTTON */}
          <CommonButton
            fullWidth
            variant="outlined"
            sx={{
              mt: 2,
            }}
            disabled={deleting}
            onClick={onClose}
          >
            Cancel
          </CommonButton>
        </Box>
      </Box>
    </Modal>
  );
}
