export const tablePalette = {
  tableTextBackground: {
    active: "#DCFCE7",
    suspended: "#FFE2E2",
    overdue: "#FEF2F2",
    surgeon: "#FFF7E9",
    disable: "#F2F2F2",
    nurse: "#FCE7F3",
    admin: "#F3E8FF",
    recovery: "#EFF6FF",
    header: "#F8FAFC",
    manager: "#DBEAFE",
    pending: "#FFFBEB",
    marketing: "#E0E7FF",
  },
  tableTextBordercolor: {
    completed: "#B9F8CF",
    pending: "#FEE685",
    inprogress: "#BEDBFF",
    overdue: "#FFC9C9",
    disable: "#E5E5E5",
    nurse: "#FAD0E3",
    admin: "#E6D6FF",
    marketing: "#D6E2FF",
  },
  tableText: {
    active: "#008236",
    suspended: "#C10007",
    surgeon: "#E9A708",
    disable: "#62748E",
    pending: "#BB4D00",
    nurse: "#C6005C",
    admin: "#8200DB",
    manager: "#1447E6",
    Trigger: "#155DFC",
    marketing: "#432DD7",
  },
  pagination: {
    main: "#E9A708",
    light: "#FFF7E9",
    dark: "#F9FAFB",
    contrastText: "#E5E7EB",
  },
};
