FROM node:20.10.0-alpine AS builder

WORKDIR /usr/src/app

RUN npm install -g pnpm@9.0.0


# Copy entire monorepo
COPY . .

# Install all dependencies
RUN pnpm install --no-frozen-lockfile

# Build all packages
RUN pnpm build

# Deploy ONLY operations-service build output
RUN pnpm deploy --filter operations-service --prod /usr/src/app/deploy


# ---------------- RUNTIME IMAGE ----------------
FROM node:20.10.0-alpine

WORKDIR /usr/src/app

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

# Copy compiled operations-service
COPY --from=builder --chown=appuser:appgroup /usr/src/app/deploy .

# Copy environment variables
COPY --chown=appuser:appgroup .env .env

USER appuser

ENV NODE_ENV=production

# Operations service port
EXPOSE 2091

CMD ["node", "dist/main.js"]
