FROM node:20.10.0-alpine AS builder

WORKDIR /usr/src/app

RUN npm install -g pnpm@9.0.0


# Copy entire monorepo
COPY . .

# Install all dependencies
RUN pnpm install --no-frozen-lockfile

# Build everything
RUN pnpm build 

# Deploy ONLY notification-service build output
RUN pnpm deploy --filter notification-service --prod /usr/src/app/deploy


# ---------------- RUNTIME IMAGE ----------------
FROM node:20.10.0-alpine

WORKDIR /usr/src/app

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

COPY --from=builder --chown=appuser:appgroup /usr/src/app/deploy .

COPY --chown=appuser:appgroup .env .env

USER appuser

ENV NODE_ENV=production

# Notification service port
EXPOSE 2093

CMD ["node", "dist/main.js"]
