import { ApprovalItem } from "./types";

export const mockApprovals: ApprovalItem[] = [
  {
    id: "1",
    patientName: "Sarah Johnson",
    formTitle: "Medical History Form",
    urgency: "High",
    submittedAt: "2025-10-30 14:23",
    status: "pending",
    summary: {
      fullName: "Sarah Johnson",
      dob: "15/03/1985",
      contact: "+44 7700 900123",
      email: "sarah.johnson@email.com",
      surgeries: "None reported",
      allergies: "Penicillin",
      medications: "None",
      notes: "Requires medical team review before approval",
    },
    formData: [],
  },
  {
    id: "2",
    patientName: "Michael Chen",
    formTitle: "Consent Form - Surgery",
    urgency: "Medium",
    submittedAt: "2025-10-30 11:15",
    status: "pending",
    summary: {
      fullName: "Michael Chen",
      dob: "11/06/1989",
      contact: "+44 7700 900321",
      email: "michael.chen@email.com",
      surgeries: "",
      allergies: "",
      medications: "",
      notes: "Requires medical team review before approval",
    },
    formData: [
      { q: "Do you have asthma or any other lung disease?", yes: true, no: false },
      { q: "Do you have epilepsy?", yes: false, no: true },
      { q: "Do you suffer high blood pressure?", yes: true, no: false },
      { q: "Do you suffer from any mental health problem?", yes: true, no: false },
      { q: "Have you ever suffered a stroke?", yes: false, no: true },
    ],
  },

  // ------- START OF 28 NEW RECORDS -------- //

  {
    id: "3",
    patientName: "Emily Carter",
    formTitle: "Medical History Form",
    urgency: "Low",
    submittedAt: "2025-10-29 09:45",
    status: "pending",
    summary: {
      fullName: "Emily Carter",
      dob: "22/07/1990",
      contact: "+44 7700 900556",
      email: "emily.carter@email.com",
      surgeries: "Appendix removal (2015)",
      allergies: "None",
      medications: "Iron supplements",
      notes: "No urgent medical concerns",
    },
    formData: [],
  },
  {
    id: "4",
    patientName: "David Wilson",
    formTitle: "Consent Form - Surgery",
    urgency: "High",
    submittedAt: "2025-10-29 10:10",
    status: "pending",
    summary: {
      fullName: "David Wilson",
      dob: "19/11/1975",
      contact: "+44 7700 900667",
      email: "david.wilson@email.com",
      surgeries: "",
      allergies: "Dust allergy",
      medications: "Atenolol",
      notes: "Review requested by cardiology team",
    },
    formData: [
      { q: "Do you have asthma or any other lung disease?", yes: false, no: true },
      { q: "Do you have epilepsy?", yes: false, no: true },
      { q: "Do you suffer high blood pressure?", yes: true, no: false },
      { q: "Do you suffer from any mental health problem?", yes: false, no: true },
      { q: "Have you ever suffered a stroke?", yes: false, no: true },
    ],
  },

  {
    id: "5",
    patientName: "Priya Sharma",
    formTitle: "Medical History Form",
    urgency: "Medium",
    submittedAt: "2025-10-28 16:12",
    status: "pending",
    summary: {
      fullName: "Priya Sharma",
      dob: "05/04/1994",
      contact: "+44 7700 900789",
      email: "priya.sharma@email.com",
      surgeries: "None",
      allergies: "Peanuts",
      medications: "Vitamin D",
      notes: "General checkup",
    },
    formData: [],
  },
  {
    id: "6",
    patientName: "John Adams",
    formTitle: "Consent Form - Surgery",
    urgency: "Low",
    submittedAt: "2025-10-28 11:38",
    status: "pending",
    summary: {
      fullName: "John Adams",
      dob: "28/02/1982",
      contact: "+44 7700 900221",
      email: "john.adams@email.com",
      surgeries: "",
      allergies: "Pollen",
      medications: "None",
      notes: "",
    },
    formData: [
      { q: "Do you have asthma or any other lung disease?", yes: false, no: true },
      { q: "Do you have epilepsy?", yes: false, no: true },
      { q: "Do you suffer high blood pressure?", yes: false, no: true },
      { q: "Do you suffer from any mental health problem?", yes: false, no: true },
      { q: "Have you ever suffered a stroke?", yes: false, no: true },
    ],
  },

  {
    id: "7",
    patientName: "Maria Gonzales",
    formTitle: "Medical History Form",
    urgency: "High",
    submittedAt: "2025-10-27 14:50",
    status: "pending",
    summary: {
      fullName: "Maria Gonzales",
      dob: "10/10/1988",
      contact: "+44 7700 900412",
      email: "maria.gonzales@email.com",
      surgeries: "C-section (2019)",
      allergies: "None",
      medications: "Thyroid medication",
      notes: "Follow-up needed",
    },
    formData: [],
  },
  {
    id: "8",
    patientName: "James Parker",
    formTitle: "Consent Form - Surgery",
    urgency: "Medium",
    submittedAt: "2025-10-27 15:30",
    status: "pending",
    summary: {
      fullName: "James Parker",
      dob: "02/01/1979",
      contact: "+44 7700 900998",
      email: "james.parker@email.com",
      surgeries: "",
      allergies: "Shellfish",
      medications: "",
      notes: "",
    },
    formData: [
      { q: "Do you have asthma or any other lung disease?", yes: true, no: false },
      { q: "Do you have epilepsy?", yes: false, no: true },
      { q: "Do you suffer high blood pressure?", yes: false, no: true },
      { q: "Do you suffer from any mental health problem?", yes: false, no: true },
      { q: "Have you ever suffered a stroke?", yes: false, no: true },
    ],
  },

  {
    id: "9",
    patientName: "Olivia Brown",
    formTitle: "Medical History Form",
    urgency: "Low",
    submittedAt: "2025-10-26 13:22",
    status: "pending",
    summary: {
      fullName: "Olivia Brown",
      dob: "30/05/1993",
      contact: "+44 7700 900523",
      email: "olivia.brown@email.com",
      surgeries: "None",
      allergies: "Dust",
      medications: "",
      notes: "",
    },
    formData: [],
  },
  {
    id: "10",
    patientName: "Robert Davis",
    formTitle: "Consent Form - Surgery",
    urgency: "High",
    submittedAt: "2025-10-26 09:50",
    status: "pending",
    summary: {
      fullName: "Robert Davis",
      dob: "12/09/1980",
      contact: "+44 7700 900654",
      email: "robert.davis@email.com",
      surgeries: "",
      allergies: "None",
      medications: "",
      notes: "Needs urgent review",
    },
    formData: [
      { q: "Do you have asthma or any other lung disease?", yes: false, no: true },
      { q: "Do you have epilepsy?", yes: true, no: false },
      { q: "Do you suffer high blood pressure?", yes: false, no: true },
      { q: "Do you suffer from any mental health problem?", yes: false, no: true },
      { q: "Have you ever suffered a stroke?", yes: false, no: true },
    ],
  },

  {
    id: "11",
    patientName: "Liam Harris",
    formTitle: "Medical History Form",
    urgency: "Medium",
    submittedAt: "2025-10-25 17:45",
    status: "pending",
    summary: {
      fullName: "Liam Harris",
      dob: "14/08/1995",
      contact: "+44 7700 900888",
      email: "liam.harris@email.com",
      surgeries: "",
      allergies: "",
      medications: "",
      notes: "",
    },
    formData: [],
  },
  {
    id: "12",
    patientName: "Emma White",
    formTitle: "Consent Form - Surgery",
    urgency: "Low",
    submittedAt: "2025-10-25 13:33",
    status: "pending",
    summary: {
      fullName: "Emma White",
      dob: "23/12/1992",
      contact: "+44 7700 900234",
      email: "emma.white@email.com",
      surgeries: "",
      allergies: "",
      medications: "",
      notes: "",
    },
    formData: [
      { q: "Do you have asthma or any other lung disease?", yes: false, no: true },
      { q: "Do you have epilepsy?", yes: false, no: true },
      { q: "Do you suffer high blood pressure?", yes: true, no: false },
      { q: "Do you suffer from any mental health problem?", yes: false, no: true },
      { q: "Have you ever suffered a stroke?", yes: false, no: true },
    ],
  },

  {
    id: "13",
    patientName: "Noah Lewis",
    formTitle: "Medical History Form",
    urgency: "High",
    submittedAt: "2025-10-24 10:10",
    status: "pending",
    summary: {
      fullName: "Noah Lewis",
      dob: "20/07/1987",
      contact: "+44 7700 900832",
      email: "noah.lewis@email.com",
      surgeries: "Knee surgery (2018)",
      allergies: "",
      medications: "",
      notes: "",
    },
    formData: [],
  },
  {
    id: "14",
    patientName: "Ava Turner",
    formTitle: "Consent Form - Surgery",
    urgency: "Medium",
    submittedAt: "2025-10-24 15:41",
    status: "pending",
    summary: {
      fullName: "Ava Turner",
      dob: "01/06/1984",
      contact: "+44 7700 900123",
      email: "ava.turner@email.com",
      surgeries: "",
      allergies: "",
      medications: "",
      notes: "",
    },
    formData: [
      { q: "Do you have asthma or any other lung disease?", yes: true, no: false },
      { q: "Do you have epilepsy?", yes: false, no: true },
      { q: "Do you suffer high blood pressure?", yes: false, no: true },
      { q: "Do you suffer from any mental health problem?", yes: true, no: false },
      { q: "Have you ever suffered a stroke?", yes: false, no: true },
    ],
  },

  {
    id: "15",
    patientName: "Benjamin Scott",
    formTitle: "Medical History Form",
    urgency: "Low",
    submittedAt: "2025-10-23 09:15",
    status: "pending",
    summary: {
      fullName: "Benjamin Scott",
      dob: "09/05/1991",
      contact: "+44 7700 901001",
      email: "benjamin.scott@email.com",
      surgeries: "",
      allergies: "",
      medications: "None",
      notes: "",
    },
    formData: [],
  },
  {
    id: "16",
    patientName: "Sophia King",
    formTitle: "Consent Form - Surgery",
    urgency: "High",
    submittedAt: "2025-10-23 11:50",
    status: "pending",
    summary: {
      fullName: "Sophia King",
      dob: "15/09/1986",
      contact: "+44 7700 901145",
      email: "sophia.king@email.com",
      surgeries: "",
      allergies: "Nuts",
      medications: "",
      notes: "",
    },
    formData: [
      { q: "Do you have asthma or any other lung disease?", yes: false, no: true },
      { q: "Do you have epilepsy?", yes: true, no: false },
      { q: "Do you suffer high blood pressure?", yes: false, no: true },
      { q: "Do you suffer from any mental health problem?", yes: false, no: true },
      { q: "Have you ever suffered a stroke?", yes: false, no: true },
    ],
  },

  {
    id: "17",
    patientName: "Daniel Moore",
    formTitle: "Medical History Form",
    urgency: "Medium",
    submittedAt: "2025-10-22 14:33",
    status: "pending",
    summary: {
      fullName: "Daniel Moore",
      dob: "11/03/1980",
      contact: "+44 7700 901234",
      email: "daniel.moore@email.com",
      surgeries: "",
      allergies: "",
      medications: "",
      notes: "",
    },
    formData: [],
  },
  {
    id: "18",
    patientName: "Mia Taylor",
    formTitle: "Consent Form - Surgery",
    urgency: "Low",
    submittedAt: "2025-10-22 15:55",
    status: "pending",
    summary: {
      fullName: "Mia Taylor",
      dob: "03/12/1990",
      contact: "+44 7700 901678",
      email: "mia.taylor@email.com",
      surgeries: "",
      allergies: "",
      medications: "",
      notes: "",
    },
    formData: [
      { q: "Do you have asthma or any other lung disease?", yes: true, no: false },
      { q: "Do you have epilepsy?", yes: false, no: true },
      { q: "Do you suffer high blood pressure?", yes: false, no: true },
      { q: "Do you suffer from any mental health problem?", yes: false, no: true },
      { q: "Have you ever suffered a stroke?", yes: false, no: true },
    ],
  },

  {
    id: "19",
    patientName: "Logan Hughes",
    formTitle: "Medical History Form",
    urgency: "High",
    submittedAt: "2025-10-21 10:42",
    status: "pending",
    summary: {
      fullName: "Logan Hughes",
      dob: "06/06/1985",
      contact: "+44 7700 902222",
      email: "logan.hughes@email.com",
      surgeries: "",
      allergies: "Gluten",
      medications: "",
      notes: "",
    },
    formData: [],
  },
  {
    id: "20",
    patientName: "Charlotte Reed",
    formTitle: "Consent Form - Surgery",
    urgency: "Medium",
    submittedAt: "2025-10-21 11:10",
    status: "pending",
    summary: {
      fullName: "Charlotte Reed",
      dob: "27/02/1993",
      contact: "+44 7700 902333",
      email: "charlotte.reed@email.com",
      surgeries: "",
      allergies: "",
      medications: "",
      notes: "",
    },
    formData: [
      { q: "Do you have asthma or any other lung disease?", yes: false, no: true },
      { q: "Do you have epilepsy?", yes: false, no: true },
      { q: "Do you suffer high blood pressure?", yes: true, no: false },
      { q: "Do you suffer from any mental health problem?", yes: false, no: true },
      { q: "Have you ever suffered a stroke?", yes: false, no: true },
    ],
  },

  {
    id: "21",
    patientName: "Ethan Hall",
    formTitle: "Medical History Form",
    urgency: "Low",
    submittedAt: "2025-10-20 09:33",
    status: "pending",
    summary: {
      fullName: "Ethan Hall",
      dob: "18/01/1989",
      contact: "+44 7700 902444",
      email: "ethan.hall@email.com",
      surgeries: "",
      allergies: "",
      medications: "",
      notes: "",
    },
    formData: [],
  },
  {
    id: "22",
    patientName: "Harper Young",
    formTitle: "Consent Form - Surgery",
    urgency: "High",
    submittedAt: "2025-10-20 12:40",
    status: "pending",
    summary: {
      fullName: "Harper Young",
      dob: "22/11/1986",
      contact: "+44 7700 902555",
      email: "harper.young@email.com",
      surgeries: "",
      allergies: "",
      medications: "",
      notes: "",
    },
    formData: [
      { q: "Do you have asthma or any other lung disease?", yes: false, no: true },
      { q: "Do you have epilepsy?", yes: true, no: false },
      { q: "Do you suffer high blood pressure?", yes: false, no: true },
      { q: "Do you suffer from any mental health problem?", yes: true, no: false },
      { q: "Have you ever suffered a stroke?", yes: false, no: true },
    ],
  },

  {
    id: "23",
    patientName: "Henry Clark",
    formTitle: "Medical History Form",
    urgency: "Medium",
    submittedAt: "2025-10-19 14:12",
    status: "pending",
    summary: {
      fullName: "Henry Clark",
      dob: "09/03/1978",
      contact: "+44 7700 902666",
      email: "henry.clark@email.com",
      surgeries: "",
      allergies: "",
      medications: "",
      notes: "",
    },
    formData: [],
  },
  {
    id: "24",
    patientName: "Isabella Wright",
    formTitle: "Consent Form - Surgery",
    urgency: "Low",
    submittedAt: "2025-10-19 16:05",
    status: "pending",
    summary: {
      fullName: "Isabella Wright",
      dob: "29/09/1991",
      contact: "+44 7700 902777",
      email: "isabella.wright@email.com",
      surgeries: "",
      allergies: "",
      medications: "",
      notes: "",
    },
    formData: [
      { q: "Do you have asthma or any other lung disease?", yes: true, no: false },
      { q: "Do you have epilepsy?", yes: false, no: true },
      { q: "Do you suffer high blood pressure?", yes: false, no: true },
      { q: "Do you suffer from any mental health problem?", yes: false, no: true },
      { q: "Have you ever suffered a stroke?", yes: false, no: true },
    ],
  },

  {
    id: "25",
    patientName: "Jack Martinez",
    formTitle: "Medical History Form",
    urgency: "High",
    submittedAt: "2025-10-18 10:20",
    status: "pending",
    summary: {
      fullName: "Jack Martinez",
      dob: "02/02/1983",
      contact: "+44 7700 902888",
      email: "jack.martinez@email.com",
      surgeries: "",
      allergies: "",
      medications: "",
      notes: "",
    },
    formData: [],
  },
  {
    id: "26",
    patientName: "Aria Foster",
    formTitle: "Consent Form - Surgery",
    urgency: "Medium",
    submittedAt: "2025-10-18 12:55",
    status: "pending",
    summary: {
      fullName: "Aria Foster",
      dob: "15/04/1990",
      contact: "+44 7700 902999",
      email: "aria.foster@email.com",
      surgeries: "",
      allergies: "",
      medications: "",
      notes: "",
    },
    formData: [
      { q: "Do you have asthma or any other lung disease?", yes: false, no: true },
      { q: "Do you have epilepsy?", yes: false, no: true },
      { q: "Do you suffer high blood pressure?", yes: true, no: false },
      { q: "Do you suffer from any mental health problem?", yes: false, no: true },
      { q: "Have you ever suffered a stroke?", yes: false, no: true },
    ],
  },

  {
    id: "27",
    patientName: "Lucas Baker",
    formTitle: "Medical History Form",
    urgency: "Low",
    submittedAt: "2025-10-17 09:55",
    status: "pending",
    summary: {
      fullName: "Lucas Baker",
      dob: "26/10/1992",
      contact: "+44 7700 903111",
      email: "lucas.baker@email.com",
      surgeries: "",
      allergies: "",
      medications: "",
      notes: "",
    },
    formData: [],
  },
  {
    id: "28",
    patientName: "Ella Ramirez",
    formTitle: "Consent Form - Surgery",
    urgency: "High",
    submittedAt: "2025-10-17 11:45",
    status: "pending",
    summary: {
      fullName: "Ella Ramirez",
      dob: "14/01/1994",
      contact: "+44 7700 903222",
      email: "ella.ramirez@email.com",
      surgeries: "",
      allergies: "",
      medications: "",
      notes: "",
    },
    formData: [
      { q: "Do you have asthma or any other lung disease?", yes: true, no: false },
      { q: "Do you have epilepsy?", yes: true, no: false },
      { q: "Do you suffer high blood pressure?", yes: false, no: true },
      { q: "Do you suffer from any mental health problem?", yes: false, no: true },
      { q: "Have you ever suffered a stroke?", yes: false, no: true },
    ],
  },

  {
    id: "29",
    patientName: "William Clark",
    formTitle: "Medical History Form",
    urgency: "Medium",
    submittedAt: "2025-10-16 13:03",
    status: "pending",
    summary: {
      fullName: "William Clark",
      dob: "08/05/1981",
      contact: "+44 7700 903333",
      email: "william.clark@email.com",
      surgeries: "",
      allergies: "",
      medications: "",
      notes: "",
    },
    formData: [],
  },
  {
    id: "30",
    patientName: "Grace Morgan",
    formTitle: "Consent Form - Surgery",
    urgency: "Low",
    submittedAt: "2025-10-16 14:28",
    status: "pending",
    summary: {
      fullName: "Grace Morgan",
      dob: "12/07/1988",
      contact: "+44 7700 903444",
      email: "grace.morgan@email.com",
      surgeries: "",
      allergies: "",
      medications: "",
      notes: "",
    },
    formData: [
      { q: "Do you have asthma or any other lung disease?", yes: false, no: true },
      { q: "Do you have epilepsy?", yes: false, no: true },
      { q: "Do you suffer high blood pressure?", yes: false, no: true },
      { q: "Do you suffer from any mental health problem?", yes: true, no: false },
      { q: "Have you ever suffered a stroke?", yes: false, no: true },
    ],
  },
];

